# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: chrisdfennell.Pickets
PackageVersion: 1.6.0
InstallerType: wix
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/chrisdfennell/Pickets/releases/download/v1.6.0/Pickets-x64.msi
  InstallerSha256: 5977DCA0CD5FC1A546D150906F419239BA6B3F24AADBE86F50F8B016BD867B76
  ProductCode: '{E71ECF49-D227-43DA-8DA5-073AB64C3217}'
- Architecture: arm64
  InstallerUrl: https://github.com/chrisdfennell/Pickets/releases/download/v1.6.0/Pickets-arm64.msi
  InstallerSha256: A042BEACB934B2AFA7466ADFEE159865E4A9925E3BD6ECD612D869292C869FB8
  ProductCode: '{16031F56-91E8-460D-905E-6589B3A85CB0}'
ManifestType: installer
ManifestVersion: 1.12.0
