# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: chrisdfennell.Pickets
PackageVersion: 1.6.0
PackageLocale: en-US
Publisher: Christopher Fennell
PrivacyUrl: https://chrisdfennell.github.io/Pickets/privacy.html
PackageName: Pickets
License: MIT License
Copyright: 2026 Christopher Fennell.
ShortDescription: Organizes your Windows desktop into movable, resizable fences.
ManifestType: defaultLocale
ManifestVersion: 1.12.0
